name: E2E Testing

on:
  [workflow_dispatch]
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup sendira
        uses: upgundecha/sendria-github-action@v1.0.0
        with:
          smtp-port: 1025
          http-port: 1080
      
      - name: Send an email
        run: |
             echo 'From: Sendria <sendria@example.com>\n To: You <you@example.com>\n Subject: Welcome!\n\n Welcome to Sendria!' | curl smtp://localhost:1025 --mail-from sendria@example.com --mail-rcpt you@example.com --upload-file -
      
      - name: Query Sendria API
        run: |
             curl localhost:1080/api/messages/
     
      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
        run: |
          echo Hello, world!
          locale
